# Generated by Django 5.0.1 on 2024-01-11 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('messages', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 11, 13, 7, 51, 13639)))),
            ],
        ),
    ]
