# Generated by Django 5.0.1 on 2024-01-11 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailmessage',
            old_name='messages',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='subcribers',
            name='date',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 11, 19, 52, 23, 372801))),
        ),
    ]
