# Generated by Django 5.0.1 on 2024-01-12 20:45

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_messages_mailmessage_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcribers',
            name='date',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 12, 21, 45, 55, 90434))),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=123)),
                ('message', ckeditor.fields.RichTextField()),
                ('recipients', models.ManyToManyField(to='base.subcribers')),
            ],
        ),
    ]
