# Generated by Django 5.0.1 on 2024-01-13 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_subcribers_date_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcribers',
            name='date',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 13, 9, 15, 48, 681308))),
        ),
        migrations.AlterField(
            model_name='subcribers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
