# Generated by Django 5.0.1 on 2024-01-14 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_subcribers_date_alter_subcribers_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='recipients',
        ),
        migrations.AlterField(
            model_name='subcribers',
            name='date',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 14, 9, 31, 15, 101908))),
        ),
    ]
