# Generated by Django 5.0.1 on 2024-01-14 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_emailtemplate_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subcriber',
            field=models.ManyToManyField(to='base.subcribers'),
        ),
        migrations.AlterField(
            model_name='subcribers',
            name='date',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 14, 11, 4, 0, 123116))),
        ),
    ]
