# Generated by Django 5.0.1 on 2024-01-20 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_subcribers_date_alter_tiplogopost_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('images', models.FileField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 20, 15, 16, 49, 514922)))),
            ],
        ),
        migrations.CreateModel(
            name='JambPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('images', models.FileField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 20, 15, 16, 49, 514922)))),
            ],
        ),
        migrations.AlterField(
            model_name='subcribers',
            name='date',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 20, 15, 16, 49, 499293))),
        ),
        migrations.AlterField(
            model_name='tiplogopost',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tiplogopost',
            name='updated_at',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 1, 20, 15, 16, 49, 514922))),
        ),
    ]
