# Generated by Django 5.0.1 on 2024-03-27 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_fishpost_jambpost_alter_subcribers_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='fishpost',
            name='updated_at',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 3, 27, 1, 30, 48, 66170))),
        ),
        migrations.AlterField(
            model_name='jambpost',
            name='updated_at',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 3, 27, 1, 30, 48, 66170))),
        ),
        migrations.AlterField(
            model_name='subcribers',
            name='date',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 3, 27, 1, 30, 48, 66170))),
        ),
        migrations.AlterField(
            model_name='tiplogopost',
            name='updated_at',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2024, 3, 27, 1, 30, 48, 66170))),
        ),
    ]
